# Generated by Django 5.2.4 on 2025-07-12 09:14

import django.core.validators
import django.utils.timezone
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("issuing_organization", models.CharField(max_length=200)),
                ("credential_id", models.CharField(blank=True, max_length=100)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("credential_url", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="certifications/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("bachelor", "Bachelor's Degree"),
                            ("master", "Master's Degree"),
                            ("phd", "PhD"),
                            ("diploma", "Diploma"),
                            ("certificate", "Certificate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("field_of_study", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-end_date", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("freelance", "Freelance"),
                            ("consulting", "Consulting"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField()),
                (
                    "achievements",
                    models.JSONField(
                        default=list, help_text="List of key achievements"
                    ),
                ),
                (
                    "technologies_used",
                    models.JSONField(
                        default=list, help_text="List of technologies used"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-start_date", "order"],
            },
        ),
        migrations.AlterModelOptions(
            name="contactmessage",
            options={"ordering": ["-sent_at"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-order", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["category", "order", "-proficiency"]},
        ),
        migrations.RemoveField(
            model_name="project",
            name="link",
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="company",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                default=portfolio.models.get_default_created_time
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="demo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="detailed_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="github_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="live_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("web_app", "Web Application"),
                    ("api", "API/Backend Service"),
                    ("mobile", "Mobile Application"),
                    ("data_science", "Data Science/AI"),
                    ("devops", "DevOps/Infrastructure"),
                    ("open_source", "Open Source"),
                    ("research", "Research Project"),
                ],
                default="web_app",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("in_progress", "In Progress"),
                    ("maintenance", "Under Maintenance"),
                    ("archived", "Archived"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.JSONField(default=list, help_text="List of technologies used"),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="category",
            field=models.CharField(
                choices=[
                    ("backend", "Backend Development"),
                    ("frontend", "Frontend Development"),
                    ("devops", "DevOps & Infrastructure"),
                    ("database", "Database & Data Engineering"),
                    ("ai_ml", "AI & Machine Learning"),
                    ("cloud", "Cloud Platforms"),
                    ("testing", "Testing & Quality Assurance"),
                    ("tools", "Development Tools"),
                    ("soft_skills", "Soft Skills"),
                ],
                default="backend",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="icon",
            field=models.CharField(
                blank=True, help_text="FontAwesome icon class", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="skill",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="skill",
            name="years_experience",
            field=models.DecimalField(
                decimal_places=1,
                default=0.0,
                help_text="Years of experience with this skill",
                max_digits=3,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="skill",
            name="proficiency",
            field=models.IntegerField(
                help_text="Skill proficiency level (0-100)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
